### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by ChrisLovering** [Xithrius/SimplePasswordGenerator#12]
I generated at password, then the program told me to copy it to a clipboard.

I got one out of my drawer, along with a pen, but then I realized the password was no where to be seen on the screen.

How can I copy it to my clipboard if I can't see it?

pls fix.

**Comment by Xithrius** [comment]
Greetings human flesh being.

Your request is currently outside the scope of this project, as I cannot access the non-metaphysical dimension from here.

**Comment by kosayoda** [comment]
the correct solution is to understand that there is no clipboard

**Comment by Xithrius** [comment]
There was never a clipboard.

**Comment by Xithrius** [comment]
@ChrisLovering I'm sorry for you to hear this, but unfortunately you have a self-deprecating case of not having a clipboard.
