### ISSUE TITLE
Merci de ne pas archiver ce repo 

### ISSUE THREAD

**Issue by Akarys42** [Xithrius/SimplePasswordGenerator#7]
Bonjour monsieur Xithirus.

Il se pourrais que j'ai pu entendre par mégarde que vous comptais clore ce repo, es ce que vous pourriez ne pas faire ceci s'il vous plaît ? 

Cordialement, 
Akarys

**Comment by Akarys42** [comment]
Je vous prierais de bien vouloir me répondre !

**Comment by Akarys42** [comment]
Je commence à perdre patience !

**Comment by Akarys42** [comment]
Monsieur Xithirus !

**Comment by Akarys42** [comment]
Cela ne va pas du tout !

**Comment by Xithrius** [comment]
À mon avis médical, le lourd est mort.

**Comment by Akarys42** [comment]
Merci pour votre réponse
